package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class nastavnik_studentUpdateController {
	@FXML
	private Label studID;
	@FXML
	private Label ime;
	@FXML
	private Label prezime;
	@FXML
	private Label smjer;
	@FXML
	private Label sifPred;
	@FXML
	private Label nazivPred;
	@FXML
	private TextField tf_bodovi;
	@FXML
	private TextField tf_ocjena;

	// Event Listener on Button.onAction
	@FXML
	public void bodoviBTN(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void ocjenaBTN(ActionEvent event) {
		// TODO Autogenerated
	}
}
